name: CI

on:
  push:
    branches: [ main ]
  #    tags:
  #      - 'v*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #      - name: Setup tmate session
      #        uses: mxschmitt/action-tmate@v3
      - name: Generate version
        run: |
          mkdir build
          echo "$(date +%Y.%-m.%d%H%M)" > build/version
          echo "${GITHUB_SHA:0:7}" > build/sha
          echo "BUILD_VERSION=$(cat build/version)" >> $GITHUB_ENV
          echo "BUILD_SHA=$(cat build/sha)" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew --stacktrace clean check yagoc-desktop:shadowJar -Pversion=$BUILD_VERSION -Psha=$BUILD_SHA
      - name: Build OSX image
        run: ./gradlew --stacktrace yagoc-desktop:createMacDmg -Pversion=$BUILD_VERSION -Psha=$BUILD_SHA
      - uses: actions/upload-artifact@v2
        with:
          name: Generic Java (Requires Java Runtime 11 or newer)
          path: yagoc-desktop/build/libs/yagoc-desktop-${{ env.BUILD_VERSION }}-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: OSX
          path: yagoc-desktop/build/distributions/*.dmg
      - uses: actions/create-release@v1
        id: create_release
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.BUILD_VERSION }}
          release_name: Release ${{ env.BUILD_VERSION }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        name: Upload Jar
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yagoc-desktop/build/libs/yagoc-desktop-${{ env.BUILD_VERSION }}-all.jar
          asset_name: Yagochess-${{ env.BUILD_VERSION }}.jar
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        name: Upload OSX .dmg
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yagoc-desktop/build/distributions/yagochess-${{ env.BUILD_VERSION }}.dmg
          asset_name: Yagochess-${{ env.BUILD_VERSION }}.dmg
          asset_content_type: application/zip
