name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #      - name: Setup tmate session
      #        uses: mxschmitt/action-tmate@v3
      - name: Generate version
        run: |
          mkdir build
          echo "$(date +%F).${GITHUB_SHA:0:7} > build/version
          cat build/version
          export VERSION=$(`cat build/version`)
      - name: Build
        run: ./gradlew --stacktrace distTar -Pversion=VERSION
      - name: Build OSX image
        run: ./gradlew --stacktrace createOSXImage -Pversion=VERSION
      - uses: actions/upload-artifact@v2
        with:
          name: Generic Java (Requires Java Runtime 15 or newer)
          path: yagoc-desktop/build/distributions/*.tar
      - uses: actions/upload-artifact@v2
        with:
          name: OSX
          path: yagoc-desktop/build/distributions/*.dmg
