name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #      - name: Setup tmate session
      #        uses: mxschmitt/action-tmate@v3
      - name: Build
        run: ./gradlew --stacktrace createOSXImage
      - uses: actions/upload-artifact@v2
        with:
          name: Generic Java 15+
          path: yagoc-desktop/build/distributions/*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: OSX - bundled JRE
          path: yagoc-desktop/Yagochess.app