name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/joschi-jdk@v2
        with:
          java-version: '8'
          architecture: x64
      - name: Build
        run: ./gradlew createOSXImage
      - uses: actions/upload-artifact@v2
        with:
          name: Generic Java 8+
          path: jenm.yagoc-desktop/build/distributions/*.zip
      - uses: actions/upload-artifact@v2
        with:
          name: OSX - bundled JRE
          path: jenm.yagoc-desktop/build/bundles/*.app